#!/usr/bin/env python3

import os
import shutil

from utils.tools import launch
from utils.common import get_file_path

import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("path")
    args = parser.parse_args()

    md_path = get_file_path('volume/report.md')
    shutil.copy(args.path, md_path)

    launch()

    report_path = get_file_path('volume/report.pdf')
    print(report_path)


if __name__ == '__main__':
    main()

