#!/usr/bin/env python3

import os
import shutil

from utils import compose
from utils.common import get_file_path


def main():
    src_path = os.getcwd()
    dest_path = get_file_path('volume')

    shutil.rmtree(dest_path)
    shutil.copytree(src_path, dest_path)

    compose.up()

    report_path = get_file_path('volume/report.pdf')
    shutil.copy(report_path, src_path)


if __name__ == '__main__':
    main()

